### ISSUE TITLE
Influence of missing side-chain atoms

### ISSUE THREAD

**Issue by j0kaso** [KULL-Centre/PRISM#10]
Related to issue #6 , it would be interesting to see if the residues which contain missing side-chain atoms would result in higher scores.

Points to take here into account: 
- [ ] differences between 1, 2 missing atoms vs. the complete side-chain missing
- [ ] 1,2 missing: which atom types lead to problems? --> likely no big influence
- [ ] which side-chains raise problems? Would an additional minimization/treatment of those residues lead to an improvement?

**Comment by amelie-stein** [comment]
I think (but have not checked) that Rosetta will rebuild the entire side chain as soon as any heavy atom is missing. On the last point, all side chains will (and I think should, though feel free to explain why not) be treated in the same way, e.g. minimisation. Also keep in mind that if there are differences by AA type, the signal will be noisy, and we already see differences in data that comes from high-quality structures. So I think it will be hard to disentangle what has to do with modelling/rebuilding here and what is a general issue with an AA in sampling and/or scoring.

**Comment by j0kaso** [comment]
So we should add this to the list & update the wiki accordingly:
[ ] when does Rosetta rebuild the missing side-chain?
[ ] is anything minimized automatically?
[ ] Do clashes occur / problematic for us?
