### ISSUE TITLE
parallelise initial relax

### ISSUE THREAD

**Issue by amelie-stein** [KULL-Centre/PRISM#15]
suggested number of structures for now is 20, let's look at a few distributions (of both score and RMSD) and we can update the number

**Comment by andershbf** [comment]
for this we can either consider making the relaxation as an array of task or we could consider compiling Rosetta with mpi and do as suggested here under parallel runs using mpi: https://www.rosettacommons.org/demos/latest/tutorials/Tips/Tips

Any opinions?

**Comment by amelie-stein** [comment]
Array task. MPI would require getting one node with multiple CPUs and good communication. Embarrassingly parallel is easier / fewer constraints.
