### ISSUE TITLE
PRISM mave file variants to mutation_file

### ISSUE THREAD

**Issue by andershbf** [KULL-Centre/PRISM#2]
Converter for PRISM mave file format to mutation file

**Comment by amelie-stein** [comment]
is "mutation file" a Rosetta mutfile?

**Comment by andershbf** [comment]
> is "mutation file" a Rosetta mutfile?

Mutation file, is the input file for the pipeline, which specifies what residues should be mutated and to what

**Comment by j0kaso** [comment]
closed with https://github.com/KULL-Centre/PRISM/commit/5d55ca8ecc403e01e1fe990a0158833f8a7ee1d2
