### ISSUE TITLE
-s input - structure or PDB_ID?

### ISSUE THREAD

**Issue by amelie-stein** [KULL-Centre/PRISM#20]
I provided a path to a PDB/coordinate file, and it failed. Providing just the identifier seems (?) to have worked. 
This needs to be better documented, and there need to be error messages explaining the user what went wrong.
It also needs to be clearly explained how to start from a structure / model.

**Comment by j0kaso** [comment]
the current pipeline is not tested (as far as I know) to allow pdb identifiers. could you send your complete submission and also which branch you're working on? The master branch is not yet the current version (I think @andershbf was going to merge dev into master).

**Comment by amelie-stein** [comment]
thx

**Comment by andershbf** [comment]
I am surprised that providing the path did not work, but it makes sense since I made a change lately, so that you are able to not provide full path and run directly from your directory. There might have come a bug from this

**Comment by j0kaso** [comment]
should be fixed - closed due to no further notes (reopen and tag otherwise 🙏 )
