### ISSUE TITLE
ddG parsing error

### ISSUE THREAD

**Issue by lydia-good** [KULL-Centre/PRISM#22]
While running pipeline stepwise, ran into an undefined variable error when calling the ddG parser (`parser_ddg_v2`):

called: `python3 /groups/sbinlab/haagenb/repository/PRISM/software/rosetta_ddG_pipeline/parser_ddg_v2.py 1PGA_relaxed A MTYKLILNGKTLKGETTTEAVDAATAEKVFKQYANDNGVDGEWTYDDATKTFTVTE /lustre/hpc/sbinlab/lgood/benchmark_Rosetta/pipeline_test/run/ddG/run/legacy_unopt /lustre/hpc/sbinlab/lgood/benchmark_Rosetta/pipeline_test/run/ddG/output /lustre/hpc/sbinlab/lgood/benchmark_Rosetta/pipeline_test/run/prepare/cleaning/structure_input_A.json`

output: ...{printed dict of all variants and three ddG scores} ```'E56P': [-257.658, -257.658, -257.658], 'E56Q': [-273.089, -273.089, -273.089], 'E56R': [-266.044, -266.044, -266.044], 'E56S': [-267.88, -267.88, -267.88], 'E56T': [-266.493, -266.493, -266.493], 'E56V': [-267.251, -267.251, -267.251], 'E56W': [-262.073, -262.166, -262.073], 'E56Y': [-261.583, -261.583, -261.583]}
Traceback (most recent call last):
  File "/groups/sbinlab/haagenb/repository/PRISM/software/rosetta_ddG_pipeline/parser_ddg_v2.py", line 89, in <module>
    parse_rosetta_ddgs(sys_name=sys.argv[1], chain_id=sys.argv[2], fasta_seq=sys.argv[3], ddG_run=sys.argv[4], ddG_output=sys.argv[5], structure_input=sys.argv[6])
  File "/groups/sbinlab/haagenb/repository/PRISM/software/rosetta_ddG_pipeline/parser_ddg_v2.py", line 53, in parse_rosetta_ddgs
    join(path_to_run_folder, rosetta_summary_file), fasta_seq))
  File "/lustre/hpc/sbinlab/haagenb/repository/PRISM/software/rosetta_ddG_pipeline/parse_cartesian_functions.py", line 53, in rosetta_cartesian_read
    return cartesian_scores,var
NameError: name 'var' is not defined```

**Comment by andershbf** [comment]
If the parser run into an a position with an error (For example, if the job was cancelled due to walltime) it will give an error. I will look into making a more robust solution for this

**Comment by j0kaso** [comment]
should be resolved due to the rerun-checks added in the last version of the pipeline
