### ISSUE TITLE
[stability-pipeline]: bug for cleaning of files which have alternative atoms

### ISSUE THREAD

**Issue by j0kaso** [KULL-Centre/PRISM#29]
given a pdb which contains alternative atoms, those are removed but the atom numbering is not changed (not continuing). This results in a Rosetta crash.

**Comment by amelie-stein** [comment]
What removes them, the preprocessing script or the Rosetta executable (or something else)? And why does it crash?

**Comment by j0kaso** [comment]
it's the Rosetta clean script which is distributed by Rosetta. But would a non-continuous atom numbering be able to cause errors in general?

Actually, my crash came from something else... fixed already

**Comment by amelie-stein** [comment]
I've never seen atom numbering matter to Rosetta. Residues, yes.

**Comment by j0kaso** [comment]
is it still an issue? I heard in WRC people talking about not using this cleaning script but maybe it was just specific cases...
