### ISSUE TITLE
Re-activate compare_mutfiles

### ISSUE THREAD

**Issue by andershbf** [KULL-Centre/PRISM#5]
Compare mutifles check need to be fixed ASAP

**Comment by j0kaso** [comment]
Can you say a bit more about the problem? I might have experienced something similar - depending on your definition ;-)

**Comment by andershbf** [comment]
It just was not compatible with some of the changes I just made in regards to alignment. Should not be any issues with the check pre-dating the newest update (06.04.2020).

If you have experience any issues, please create an issue, or PM me and we can discuss it :)

**Comment by j0kaso** [comment]
fixed
