### ISSUE TITLE
Treatment of missing non-heavy, side-chain atoms

### ISSUE THREAD

**Issue by j0kaso** [KULL-Centre/PRISM#6]
Are they treated during the relax step (automatically)? It would be good to add this info to "the" documentation.

**Comment by amelie-stein** [comment]
I'm not sure I understand the question. They are missing, and there is no simple way to fill them in. Constrained relax has per-atom constraints so this should not matter. For unrelaxed constraints we should look into what happens, I am not sure. But missing atoms are common so I suspect there is a reasonably safe default - but best check on well-known examples. We can also chat about it later.

**Comment by j0kaso** [comment]
Clarification: it's about missing non-heavy backbone atoms

Some ideas with regards to this:
- [X] "when": during the relax step but this is not monitored --> good to know for everyone! 
- [ ] Although it seems to be a Rosetta standard, we should add this as a comment to the documentation (e.g. in the sbinlab wiki).
- [ ] We should include a check-step in the pipeline, that all missing atom issues are resolved before the ddG calculation

**Comment by amelie-stein** [comment]
Since Rosetta will always rebuild the missing atoms, I don't think you need that last check. Also keep in mind that all this is rather specific to crystal structures, but a large part of our likely "application targets" are homology models, where everything will have been built by Rosetta - heavily inspired by experimental structures, yes, but all the details such as side chains will have been placed by Rosetta.

**Comment by j0kaso** [comment]
listening a bit to some Rosetta community conversations, we should add a check to see that modeled side-chains do not contain clashes. I guess Rosetta is printing this out, so we could just re-use that?

**Comment by amelie-stein** [comment]
I think this will be addressed by the relax step, between the repacking and minimisation that it does. Or is this a concern being discussed post-relaxation?

**Comment by j0kaso** [comment]
it still is not resolved (in some cases) post-relaxation. I would just make everyone aware of it (& maybe be able to catch the error automatically) and then see how often this happens & evaluate then how we can improve this.

**Comment by amelie-stein** [comment]
Ok thanks. I do think this would implicitly be covered if we keep per-residue energies, especially if we also keep partial sfxn terms (fa_rep in this case).

**Comment by j0kaso** [comment]
Notes added in 1ddabfb8afd0d8483c843169f4028cf05fcc1fb8
