### ISSUE TITLE
Keep chain flag problem 

### ISSUE THREAD

**Issue by AleksandraPanfilova** [KULL-Centre/PRISM#80]
When chains are not in the same order as in .pdb file, mutfile renumbering to Rosetta numbering is wrong.

When --run_struc BA and actual order is A, B.

**Comment by j0kaso** [comment]
should be fixed now [6c7aeed](https://github.com/KULL-Centre/PRISM/commit/6c7aeed53a7585f91a514967b484f6c272520b4e)
